### PR TITLE
ROASTER-128: Additional checks to prevent illegal imports

### PR DESCRIPTION
**Pull request by gastaldi**
Co-authored-by: Kai Müller <15907922+kaijMueller@users.noreply.github.com>

### CODE REVIEW

**Comment by gastaldi** [comment]
@kaijMueller after pondering for some time, the easiest way to avoid refactoring a considerable number of classes is to just change the import to use the MockAnnotation in the correct package and to move the `isValidImport` method you had to the existing `validImport`

**Comment by kaijMueller** [comment]
@gastaldi: Looking good for me. Any additional actions required from my side?
Thank you for the support?

**Comment by gastaldi** [comment]
@kaijMueller thank you very much for your help!

**Comment by kaijMueller** [comment]
@gastaldi : Do you know when I can expect the fix in a release?

**Comment by kaijMueller** [comment]
Thank you!

**Pull request merged**
