### PR TITLE
Roaster 35

### PR DESCRIPTION
**Pull request by stovocor**
Adding PropertyHolderSource.getProperties(Class<?>) with test case, some cleanup.

### CODE REVIEW

**Comment by gastaldi** [comment]
Thank you!

**Comment by gastaldi** [comment]
Can you assign the issue to yourself?

**Comment by stovocor** [comment]
No, I do not have the required permissions.

**Comment by stovocor** [comment]
Hm, it seems "start progress" assigns an issue to me. Looks like ROASTER-71 is my next bug. :)

**Pull request merged**
