### PR TITLE
Support Javadoc in AnnotationElement

### LINKED ISSUE #271: Support JavaDoc comment to an annotation element
### Discussed in https://github.com/forge/roaster/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **rob-stoecklein** November  8, 2022</sup>
When creating an annotation type, how do we set the JavaDoc for an element?
In the example below, it's the JAVADOC TEXT.

```
    /**
     * Trying to build the following annotation:
     * 
     * public @interface MyAnnotation {
     *
     *     /**
     *      * JAVADOC TEXT
     *      */
     *     String element;
     * }
     */
    public static void main(final String[] args) {
        final JavaAnnotationSource output = Roaster.create(JavaAnnotationSource.class);
        output.setName("MyAnnotation");

        final AnnotationElementSource annotationElementSource = output.addAnnotationElement();
        annotationElementSource.setName("element");
        annotationElementSource.setType("String");
        //annotationElementSource.getJavaDoc().setFullText("JAVADOC TEXT");  // <== Expecting a call like this

        final String outputStr = Roaster.format(output.toString());
        System.out.println(outputStr);
    }
```

How can we get this to work?
Thanks!
</div>

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #271

### CODE REVIEW

**Comment by rob-stoecklein** [comment]
This fixes the "annotation element JavaDoc" problem, as I can now run the simple test program okay.
However, this **breaks** our existing code when I attempt to run our full application.

Running:
```
output.addInterface("com.blah.blah.blah.ConfigAware<T>"); // output is of type InterfaceCapableSource<?>
```
gives the following exception stack trace:
```
java.lang.IllegalArgumentException: Invalid identifier : >ConfigAware<T><
	at org.jboss.forge.roaster._shade.org.eclipse.jdt.core.dom.SimpleName.setIdentifier(SimpleName.java:247)
	at org.jboss.forge.roaster._shade.org.eclipse.jdt.core.dom.AST.newSimpleName(AST.java:2793)
	at org.jboss.forge.roaster._shade.org.eclipse.jdt.core.dom.AST.newName(AST.java:2443)
	at org.jboss.forge.roaster.model.impl.AbstractInterfaceCapableJavaSource.addInterface(AbstractInterfaceCapableJavaSource.java:94)
	at com.tccc.kos.sdk.generator.builder.TypeBase.copyInterfaces(TypeBase.java:320)
	at com.tccc.kos.sdk.generator.builder.TypeClass.parse(TypeClass.java:34)
```
It happens because the target class implements the `ConfigAware<T>` interface.

Any ideas?
Was there a recent change to this code? (It works as expected in version 2.26.0.Final)

**Comment by rob-stoecklein** [comment]
I also get this error when I use v2.27.0.Final, so it has something to do with going from 2.26.0 to 2.27.0.

I see one thing that changed is  `org.eclipse.jdt.core`, which went from v3.30.0 to v3.31.0.

**Comment by gastaldi** [comment]
@rob-stoecklein good catch! I pushed a fix to master and rebased this PR. Can you give it a try now? I'll release the next version once you confirm it's okay

**Comment by rob-stoecklein** [comment]
@gastaldi It now works like a champ -- thanks!

**Comment by rob-stoecklein** [comment]
We do you think 2.28.0 will be pushed to the Central repo?

**Comment by gastaldi** [comment]
@rob-stoecklein I just released to Central, should be there in a few minutes

**Comment by gastaldi** [comment]
It's there now, enjoy! https://repo1.maven.org/maven2/org/jboss/forge/roaster/roaster-jdt/2.28.0.Final/roaster-jdt-2.28.0.Final.pom

**Comment by rob-stoecklein** [comment]
Excellent -- thank you!

**Pull request merged**
