### PR TITLE
Improve Strings utility

### PR DESCRIPTION
**Pull request by kaijMueller**
I refactored the string utility

### CODE REVIEW

**Comment by gastaldi** [comment]
LGTM, but perhaps we could depend on commons-text and let the shade plug-in grab this single class?

**Comment by kaijMueller** [comment]
> shade plug-in

What is the shade plug-in. I'm fine with basing on commons-text. Less code to maintain :-D

**Comment by gastaldi** [comment]
This is the shade plug-in: https://github.com/forge/roaster/blob/master/impl/pom.xml#L57

**Comment by gastaldi** [comment]
Superseded by https://github.com/forge/roaster/pull/109

**Pull request closed without merging**
