### PR TITLE
Support arrays in Types.toSimpleName().

### PR DESCRIPTION
**Pull request by Meijuh**
- add the generics before the array declaration
- add unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/forge/roaster/66)

### CODE REVIEW

**Comment by Meijuh** [comment]
My account at the issue tracker was not yet verified, so was not able to create an issue for this pull request.

**Comment by Meijuh** [comment]
Btw, to reproduce a bug that is caused by this, run: `        Roaster.create(JavaEnumSource.class).addProperty("Class<?>[]", "foobar");`

**Comment by gastaldi** [comment]
Ok to test

**Comment by gastaldi** [comment]
Thanks for the PR. Can you add a test to the bug you described too?

**Comment by gastaldi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/forge/roaster/66)*

**Comment by gastaldi** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/forge/roaster/66#-:-KOz1gDurw5yVkfyiS3H:bnfp4nl)*

**Pull request merged**
