### PR TITLE
updated class path

### PR DESCRIPTION
**Pull request by Plamen5kov**
The class path pointed to an non existing directory and could not find the `Boostrap` class. 

_problem_
When `./roaster` command was called, it gave error:
`Error: Could not find or load main class org.jboss.forge.roaster.Bootstrap`

_steps to reproduce_
* `git clone git@github.com:forge/roaster.git`
* `cd roaster`
* `mvn compile`
* `cd dist/target/classes/bin`
* `./roaster`
the error previously mentioned happens at this point.

### CODE REVIEW

**Comment by gastaldi** [comment]
Ok to test

**Comment by Plamen5kov** [comment]
I just noticed, the thing I tested is the `.jar` distribution and the compiled classes. In the `.zip` distribution the classes are packed inside the `lib/` folder and everything seems to be working. I suggest packaging the `.zip` and `.jar` files the same way to avoid future confusion, either with or without the `lib/` folder.

**Comment by gastaldi** [comment]
Hi, thanks for the PR.

Why not add both directories to the classpath? That would solve both problems, no?

**Comment by gastaldi** [comment]
Thanks, that looks good

**Pull request merged**
