### PR TITLE
Simplified `AbstractJavaSourceMemberHolder#addInterface(java.lang.String)`

### LINKED ISSUE #259: Wrong code generated when extending interface with another that has the same name
When extending an interface with another one that has the same name but comes from a different package, Roaster should add a fully qualified reference to the extending interface.
Here is a reproducer that can be run using `jbang`:

```
///usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS org.jboss.forge.roaster:roaster-api:2.26.0.Final
//DEPS org.jboss.forge.roaster:roaster-jdt:2.26.0.Final

import org.jboss.forge.roaster.Roaster;
import org.jboss.forge.roaster.model.source.JavaInterfaceSource;

import static java.lang.System.out;

class Bug {

	public static void main(String[] args) {

		JavaInterfaceSource outer = Roaster.create(JavaInterfaceSource.class)
				.setPackage("outer")
				.setName("Buggy")
				.setPublic();

		JavaInterfaceSource inner = Roaster.create(JavaInterfaceSource.class)
				.setPackage("outer.inner")
				.setName("Buggy")
				.setPublic();

		inner.addInterface(outer);

		out.println("Expected:\n" +
				"package outer.inner;\n" +
				"public interface Buggy extends outer.Buggy {\n" +
				"}");

		out.println("Actual:");
		out.println(inner.toString());
	}
}
```
Is there a workaround (other than changing the name)? Thanks for any help!

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #259

### CODE REVIEW

**Comment by gastaldi** [comment]
@Jsenko can you check if this fix works for you? Thanks!

**Comment by jsenko** [comment]
Hi @gastaldi , it works now! Thanks for the quick response. Would you consider releasing 2.26.1 in the near future?

**Comment by gastaldi** [comment]
Sure, just waiting for a review from @lincolnthree before proceeding 😉

**Comment by gastaldi** [comment]
@jsenko I pushed another change, can you let me know if that still works for you?

**Pull request merged**
