### PR TITLE
ROASTER-92 : implementInterface shouldn't copy annotation 

### PR DESCRIPTION
**Pull request by nchal**
I add removeAnnotations method on all annotations holder.
Then a call this method on methodSource and all parameter of implemented
methods.

### CODE REVIEW

**Comment by gastaldi** [comment]
There is still something wrong with your environment. I can't see what has changed, as the "Files changed" tab shows that the file has changed completely. Also, it seems that you have added the commit to ROASTER-92. Can you fix this? Do you need any help?

**Comment by nchal** [comment]
Yes, I think I need help... I don't understand :'(

**Comment by gastaldi** [comment]
First of all make sure your project is set up as it follows:

**Comment by gastaldi** [comment]
First, make sure your project is set up as in the following pic:

screenshot from 2016-01-20 09-52-08

**Pull request closed without merging**
